name: Run Python Script and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 8 * * 1-5'     # 08:00 UTC weekdays
  workflow_dispatch:

permissions:
  contents: write             # needed for pushes

jobs:
  run-main-script:
    runs-on: ubuntu-latest

    # ▸▸▸  expose the secret to every step in this job  ◂◂◂
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt        # fredapi, bs4, etc.

    - name: Run main script
      run: python main_remote.py                  # generates HTML + charts

    - name: Set up Git identity
      run: |
        git config --global user.name  'ndaly111'
        git config --global user.email 'ndaly111@gmail.com'

    - name: Commit and push changes to main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Update website content" --allow-empty
        git push https://ndaly111:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main --force

    # ---- deploy to gh-pages --------------------------------------------------
    - name: Clone main branch into sub-folder
      uses: actions/checkout@v4
      with:
        ref: main
        path: main_repo

    - name: Check out gh-pages branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone --branch gh-pages https://ndaly111:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
        rsync -a --delete main_repo/ gh-pages/      # mirror files

    - name: Commit and push to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages" --allow-empty
        git push https://ndaly111:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages --force
