name: Run Python Script and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 8 * * 1-5'        # run 08:00 UTC Mon-Fri
  workflow_dispatch:

permissions:
  contents: write                # allow pushes from the action

jobs:
  run-main-script:
    runs-on: ubuntu-latest

    # ✱ NEW: surface the secret so generate_economic_data.py can read it
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

    steps:
    # ------------------------------------------------------------------ checkout main
    - name: Check out repository
      uses: actions/checkout@v2

    # ------------------------------------------------------------------ python setup
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt      # fredapi, bs4, etc.

    # ------------------------------------------------------------------ build site
    - name: Run main script
      run: python main_remote.py                # generates HTML + charts

    # ------------------------------------------------------------------ commit to main
    - name: Set up Git identity
      run: |
        git config --global user.name  'ndaly111'
        git config --global user.email 'ndaly111@gmail.com'

    - name: Commit and push changes to main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Update website content" --allow-empty
        git push https://ndaly111:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main --force

    # ------------------------------------------------------------------ deploy to gh-pages
    - name: Clone main branch into sub-folder
      uses: actions/checkout@v2
      with:
        ref: main
        path: main_repo                       # local folder holding site files

    - name: Check out gh-pages branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone --branch gh-pages \
          https://ndaly111:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages

        # copy everything *except* dot-files like .git
        shopt -s dotglob nullglob
        cp -r main_repo/* gh-pages/

    - name: Commit and push changes to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages" --allow-empty
        git push https://ndaly111:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages --force
