name: Run Python Script and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 8 * * 1-5'        # 08:00 UTC weekdays
  workflow_dispatch:

permissions:
  contents: write                # allow pushes with GITHUB_TOKEN

jobs:
  run-main-script:
    runs-on: ubuntu-latest
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

    steps:
    # ────────────── 1. check out main ──────────────
    - name: Check out repository
      uses: actions/checkout@v4

    # ────────────── 2. python setup ────────────────
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    # ────────────── 3. build the site ──────────────
    - name: Run main script
      run: python main_remote.py              # writes HTML & charts

    # ────────────── 4. git identity ───────────────
    - name: Set up Git identity
      run: |
        git config --global user.name  'ndaly111'
        git config --global user.email 'ndaly111@gmail.com'

    # ────────────── 5. commit to main if changed ──
    - name: Detect file changes on main
      id: chk_main
      run: |
        if git diff --quiet; then
          echo "changed=false" >> "$GITHUB_OUTPUT"
        else
          echo "changed=true"  >> "$GITHUB_OUTPUT"
        fi

    - name: Commit & push changes to main
      if: steps.chk_main.outputs.changed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Update website content"
        git push origin main

    # ────────────── 6. prepare gh-pages ────────────
    - name: Check out gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: Sync built files into gh-pages
      run: |
        rsync -av --delete --exclude='.git' ./ gh-pages/

    # ────────────── 7. commit to gh-pages if changed
    - name: Detect file changes on gh-pages
      id: chk_pages
      run: |
        cd gh-pages
        if git diff --quiet; then
          echo "changed=false" >> "$GITHUB_OUTPUT"
        else
          echo "changed=true"  >> "$GITHUB_OUTPUT"
        fi

    - name: Commit & push changes to gh-pages
      if: steps.chk_pages.outputs.changed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages
