name: Run Python Script

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-main-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run main script
      run: python main_remote.py

    - name: Checkout gh-pages branch
      run: git checkout -b gh-pages origin/gh-pages

    - name: Copy HTML to root
      run: cp charts/financial_charts.html ./  # Adjust the path if your HTML is generated elsewhere

    - name: Commit and push
      run: |
        git config --global user.name 'ndaly111'
        git config --global user.email 'ndaly111@gmail.com'
        git add financial_charts.html
        git commit -m "Update HTML report"
        git push origin gh-pages --force
      env:
        GITHUB_TOKEN: ${{ secrets.HTML_ACCESS }}
