name: Run Python Script and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 8 * * 1-5'          # 08:00 UTC weekdays
  workflow_dispatch:

permissions:
  contents: write                  # allow this Action to push commits

jobs:
  run-main-script:
    runs-on: ubuntu-latest

    # ①  NEW — surface your FRED API key for the Python code
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

    steps:
    # ---------------------------------------------------------------- checkout main
    - name: Check out repository
      uses: actions/checkout@v2

    # ---------------------------------------------------------------- Python setup
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt        # fredapi, bs4, …

    # ---------------------------------------------------------------- build site
    - name: Run main script
      run: python main_remote.py                  # writes HTML + charts

    # ---------------------------------------------------------------- git config
    - name: Set up Git identity
      run: |
        git config --global user.name  'ndaly111'
        git config --global user.email 'ndaly111@gmail.com'

    # ②  OPTIONAL — bail out early if nothing changed on main
    - name: Abort if no file changes (main)
      run: |
        git diff --quiet && echo "No changes → skip push." && exit 0 || echo "Changes detected"
      id: chk_main

    # ---------------------------------------------------------------- commit to main
    - name: Commit and push changes to main
      if: steps.chk_main.outcome == 'success'   # only runs when changes exist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Update website content"
        git push https://ndaly111:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main --force

    # ---------------------------------------------------------------- clone main into temp dir
    - name: Clone repository (main → main_repo/)
      uses: actions/checkout@v2
      with:
        ref: main
        path: main_repo

    # ---------------------------------------------------------------- prepare / update gh-pages
    - name: Check out gh-pages branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone --branch gh-pages \
          https://ndaly111:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
        cd gh-pages
        cp -r ../main_repo/* .               # identical to your original copy command

    # ---------------------------------------------------------------- push gh-pages
    - name: Commit and push changes to gh-pages
      if: steps.chk_pages.outcome == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push https://ndaly111:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages --force
