name: Run Python Script

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-main-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use the version of Python you need

    - name: Install dependencies
      run: pip install -r requirements.txt  # Assumes you have a requirements.txt file

    - name: Run main script
      run: python main_remote.py  # Replace this with the path to your Python script

    - name: Configure Git
      run: |
        git config --global user.name 'ndaly111'
        git config --global user.email 'ndaly111@gmail.com'

    - name: Push changes
      run: |
        git commit -m "Update HTML report" --allow-empty
        git push --force "https://${{ secrets.HTML_ACCESS }}@github.com/ndaly111/StockFinances.git" gh-pages
