name: Segment revenue TXT (manual)

on:
  workflow_dispatch: {}        # run from the Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      Email: ${{ secrets.Email }}      # make sure the secret is named “Email”

    steps:
      # 1️⃣  Check out code
      - uses: actions/checkout@v4

      # 2️⃣  Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3️⃣  Install everything in requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣  Run the script
      - name: Run segment report
        run: python segment_revenue_report.py

      # 5️⃣  Commit updated output file (if generated)
      - name: Commit report
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name  "github-actions"
          git add segment_report.txt || true
          git commit -m "Update segment_report.txt" || echo "No changes"
          git push
