name: patch-implied-growth-2025-08-05   # appears in Actions list

on:
  workflow_dispatch:                    # manual trigger only

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run one-off patch script
        run: python patch_2025_08_05_implied_growth_fix.py

      - name: Commit & push updated DB
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "GitHub Action"
          git config user.email "action@users.noreply.github.com"
          if git diff --quiet "Stock Data.db"; then
            echo "No DB changes – nothing to commit."
          else
            git add "Stock Data.db"
            git commit -m "patch: correct implied growth for 2025-08-05"
            git push
          fi
